In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
from scipy.stats import zscore
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("all_data.csv")

In [3]:
supplier_return = pd.read_csv("data/supplier_return.csv")

In [4]:
df = df.merge(supplier_return, on="supplier_id")

In [5]:
df.head()

,order_date,user_id,is_elite_user,supplier_id,order_line_item_id,order_parent_id,product_content_id,product_variant_id,original_price,discounted_price,...,gender_name_y,category_id_y,category_name_y,color_id_y,color_name_y,supplier_color_name_y,attributet_name_y,attribute_value_y,defective_returnRate,returnRate_y
0,2021-05-01 00:00:01.761000+00:00,3941815,0,4662,901280147,595758968,95503167,159147197,79.9,51.94,...,Erkek,604,T-Shirt,6998.0,Beyaz,Beyaz,BEDEN,XL,0.003045,0.098178
1,2021-05-01 00:11:01.908000+00:00,846261,0,4662,901317372,595779437,97027250,161565995,14.9,11.92,...,Kadın / Kız,550,Çorap,7009.0,Siyah,Siyah / Saks Mavi,BEDEN,36/40,0.003045,0.098178
2,2021-05-01 00:27:09.965000+00:00,244942,1,4662,901366867,595806906,62212612,108756538,69.9,38.45,...,Erkek,525,Eşofman Altı,7009.0,Siyah,Siyah,BEDEN,11 Yaş,0.003045,0.098178
3,2021-05-01 00:27:51.300000+00:00,45974971,1,4662,901368497,595807996,79870825,135408496,49.9,32.44,...,Erkek,604,T-Shirt,6998.0,Beyaz,Beyaz,BEDEN,M,0.003045,0.098178
4,2021-05-01 01:10:44.282000+00:00,22708302,1,4662,901478384,595867189,89451047,149564473,129.9,84.44,...,Erkek,525,Eşofman Altı,7009.0,Siyah,Siyah,BEDEN,XL,0.003045,0.098178

In [6]:
df = df.drop(['product_id_y', 'product_name_y', 'brand_id_y',
       'brand_name_y', 'gender_id_y', 'gender_name_y', 'category_id_y',
       'category_name_y', 'color_id_y', 'color_name_y',
       'supplier_color_name_y', 'attributet_name_y', 'attribute_value_y','coupon_id','promotion_name','promotion_award_value','defective_returnRate_x','defective_returnRate_y'], axis = 1)

In [7]:
df.head()

,order_date,user_id,is_elite_user,supplier_id,order_line_item_id,order_parent_id,product_content_id,product_variant_id,original_price,discounted_price,...,gender_name_x,category_id_x,category_name_x,color_id_x,color_name_x,supplier_color_name_x,attributet_name_x,attribute_value_x,defective_returnRate,returnRate_y
0,2021-05-01 00:00:01.761000+00:00,3941815,0,4662,901280147,595758968,95503167,159147197,79.9,51.94,...,Erkek,604,T-Shirt,6998.0,Beyaz,Beyaz,BEDEN,XL,0.003045,0.098178
1,2021-05-01 00:11:01.908000+00:00,846261,0,4662,901317372,595779437,97027250,161565995,14.9,11.92,...,Kadın / Kız,550,Çorap,7009.0,Siyah,Siyah / Saks Mavi,BEDEN,36/40,0.003045,0.098178
2,2021-05-01 00:27:09.965000+00:00,244942,1,4662,901366867,595806906,62212612,108756538,69.9,38.45,...,Erkek,525,Eşofman Altı,7009.0,Siyah,Siyah,BEDEN,11 Yaş,0.003045,0.098178
3,2021-05-01 00:27:51.300000+00:00,45974971,1,4662,901368497,595807996,79870825,135408496,49.9,32.44,...,Erkek,604,T-Shirt,6998.0,Beyaz,Beyaz,BEDEN,M,0.003045,0.098178
4,2021-05-01 01:10:44.282000+00:00,22708302,1,4662,901478384,595867189,89451047,149564473,129.9,84.44,...,Erkek,525,Eşofman Altı,7009.0,Siyah,Siyah,BEDEN,XL,0.003045,0.098178

In [8]:
df.columns

Index(['order_date', 'user_id', 'is_elite_user', 'supplier_id',
       'order_line_item_id', 'order_parent_id', 'product_content_id',
       'product_variant_id', 'original_price', 'discounted_price', 'ship_cost',
       'coupon_discount', 'is_wallet_trx', 'is_saved_card_trx', 'is_returned',
       'returnRate_x', 'total_claim', 'unresolved_claim',
       'unresolved_accepted_claim', 'unresolvedclaim_percentage',
       'review_rates_mean', 'review_rates_min', 'review_rates_max',
       'product_id_x', 'product_name_x', 'brand_id_x', 'brand_name_x',
       'gender_id_x', 'gender_name_x', 'category_id_x', 'category_name_x',
       'color_id_x', 'color_name_x', 'supplier_color_name_x',
       'attributet_name_x', 'attribute_value_x', 'defective_returnRate',
       'returnRate_y'],
      dtype='object')

In [9]:
with open("user_return_ratio.txt") as f:
    user_return_ratio = eval(f.read())

In [10]:
df["user_return_ratio"] = df["user_id"].apply(lambda x: user_return_ratio[x])

In [11]:
group_cols = ["user_id", "product_content_id", "order_parent_id"]

In [12]:
df.head()

,order_date,user_id,is_elite_user,supplier_id,order_line_item_id,order_parent_id,product_content_id,product_variant_id,original_price,discounted_price,...,category_id_x,category_name_x,color_id_x,color_name_x,supplier_color_name_x,attributet_name_x,attribute_value_x,defective_returnRate,returnRate_y,user_return_ratio
0,2021-05-01 00:00:01.761000+00:00,3941815,0,4662,901280147,595758968,95503167,159147197,79.9,51.94,...,604,T-Shirt,6998.0,Beyaz,Beyaz,BEDEN,XL,0.003045,0.098178,0.125000
1,2021-05-01 00:11:01.908000+00:00,846261,0,4662,901317372,595779437,97027250,161565995,14.9,11.92,...,550,Çorap,7009.0,Siyah,Siyah / Saks Mavi,BEDEN,36/40,0.003045,0.098178,0.230769
2,2021-05-01 00:27:09.965000+00:00,244942,1,4662,901366867,595806906,62212612,108756538,69.9,38.45,...,525,Eşofman Altı,7009.0,Siyah,Siyah,BEDEN,11 Yaş,0.003045,0.098178,0.168675
3,2021-05-01 00:27:51.300000+00:00,45974971,1,4662,901368497,595807996,79870825,135408496,49.9,32.44,...,604,T-Shirt,6998.0,Beyaz,Beyaz,BEDEN,M,0.003045,0.098178,0.036232
4,2021-05-01 01:10:44.282000+00:00,22708302,1,4662,901478384,595867189,89451047,149564473,129.9,84.44,...,525,Eşofman Altı,7009.0,Siyah,Siyah,BEDEN,XL,0.003045,0.098178,0.028571

In [13]:
df.drop_duplicates(subset =group_cols,
                     keep = False, inplace = True)

In [14]:
sum(df[group_cols].duplicated())

0

In [15]:
df["order_date"] = pd.to_datetime(df["order_date"])
df.sort_values("order_date", inplace=True)

In [16]:
train = df[df.order_date <= "2021-07-31"]
test = df[df.order_date > "2021-07-31"]

In [17]:
#train.to_csv("train_all.csv", index=False)
#test.to_csv("test_all.csv", index=False)

In [18]:
train = pd.read_csv("train_all.csv")

In [19]:
train = train.drop(["order_date", 'gender_name_x','category_name_x','category_name_x','brand_name_x','product_name_x','supplier_color_name_x','attributet_name_x','color_name_x'], axis =1)

In [20]:
train = train.drop('attribute_value_x', axis =1)

In [21]:
train["is_saved_card_trx"] = train["is_saved_card_trx"].replace({True: 1, False: 0})

In [22]:
train["is_saved_card_trx"] = train["is_saved_card_trx"].replace({True: 1, False: 0})

In [23]:
train['ship_cost'] = train['ship_cost'].fillna(5)

In [24]:
train.columns

Index(['user_id', 'is_elite_user', 'supplier_id', 'order_line_item_id',
       'order_parent_id', 'product_content_id', 'product_variant_id',
       'original_price', 'discounted_price', 'ship_cost', 'coupon_discount',
       'is_wallet_trx', 'is_saved_card_trx', 'is_returned', 'returnRate_x',
       'total_claim', 'unresolved_claim', 'unresolved_accepted_claim',
       'unresolvedclaim_percentage', 'review_rates_mean', 'review_rates_min',
       'review_rates_max', 'product_id_x', 'brand_id_x', 'gender_id_x',
       'category_id_x', 'color_id_x', 'defective_returnRate', 'returnRate_y',
       'user_return_ratio'],
      dtype='object')

In [25]:
train_0 = train[train.is_returned == 0]
train_1 = train[train.is_returned == 1]

In [26]:
train_0.isna().sum()

user_id                          0
is_elite_user                    0
supplier_id                      0
order_line_item_id               0
order_parent_id                  0
product_content_id               0
product_variant_id               0
original_price                   0
discounted_price                 0
ship_cost                        0
coupon_discount                  0
is_wallet_trx                    0
is_saved_card_trx                0
is_returned                      0
returnRate_x                     0
total_claim                      0
unresolved_claim                 0
unresolved_accepted_claim        0
unresolvedclaim_percentage       0
review_rates_mean                0
review_rates_min                 0
review_rates_max                 0
product_id_x                     0
brand_id_x                       0
gender_id_x                   1107
category_id_x                    0
color_id_x                     643
defective_returnRate             0
returnRate_y                     0
user_return_ratio                0
dtype: int64

In [27]:
train = train.drop(["gender_id_x","color_id_x"], axis =1)

In [28]:
z_score = zscore(train_0[['original_price', 'discounted_price', 'coupon_discount', "returnRate_x",
   "total_claim", "unresolved_claim", "unresolved_accepted_claim", "unresolvedclaim_percentage",
    "defective_returnRate", "review_rates_mean", "review_rates_min", "review_rates_max"]])

In [29]:
abs_zscore = abs(z_score)
train_0 = train_0[(abs_zscore < 2).all(axis=1)]

In [30]:
train_zscore = pd.concat([train_0, train_1])

In [31]:
train_zscore = pd.concat([train_0, train_1])

In [32]:
#train_zscore.to_csv("train_zscore.csv", index=False)

In [33]:
drop_cols = ['user_id', 'product_content_id', 'order_parent_id', 'is_returned',"returnRate_y"]

In [34]:
df_sampled = train.sample(n=30000, random_state=42)

X = df_sampled.drop(columns="is_returned", axis=1)
y = df_sampled["is_returned"]

In [35]:
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# Import necessary modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=40)

In [37]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(256,256,256,256,256), activation='relu', solver='adam',early_stopping=True, max_iter=200)
mlp.fit(X_train,y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [38]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,predict_train))
print(classification_report(y_train,predict_train))

[[18304    42]
 [ 2649     5]]
              precision    recall  f1-score   support

         0.0       0.87      1.00      0.93     18346
         1.0       0.11      0.00      0.00      2654

    accuracy                           0.87     21000
   macro avg       0.49      0.50      0.47     21000
weighted avg       0.78      0.87      0.81     21000

In [39]:
print(confusion_matrix(y_test,predict_test))
print(classification_report(y_test,predict_test))

[[7811   15]
 [1167    7]]
              precision    recall  f1-score   support

         0.0       0.87      1.00      0.93      7826
         1.0       0.32      0.01      0.01      1174

    accuracy                           0.87      9000
   macro avg       0.59      0.50      0.47      9000
weighted avg       0.80      0.87      0.81      9000